alter table ALUNO drop constraint FK3B7CCCBA49A6E6E;
alter table ALUNO_QUESTIONARIO drop constraint FKD7B490F18066DC;
alter table ALUNO_QUESTIONARIO drop constraint FKD7B490F153CA793F;
alter table ALUNO_TURMA drop constraint FK2F23C2D1D07D5016;
alter table ALUNO_TURMA drop constraint FK2F23C2D153CA793F;
alter table PROFESSOR drop constraint FK69F5E64FA49A6E6E;
alter table QUESTAO_ALTERNATIVA drop constraint FKF6AFF23AF603D5DF;
alter table QUESTAO_ALTERNATIVA drop constraint FKF6AFF23A5F49DEDE;
alter table QUESTIONARIO drop constraint FK7FE291FD374CDDF5;
alter table QUESTIONARIO drop constraint FK7FE291FD53CA793F;
alter table QUESTIONARIO drop constraint FK7FE291FDE175AEFF;
alter table QUESTIONARIO_RESPOSTA drop constraint FK63C7A3232FB1E4A4;
alter table QUESTIONARIO_RESPOSTA drop constraint FK63C7A323253A7595;
alter table RESPOSTA drop constraint FK1A5D1721E210B8BF;
alter table RESPOSTA drop constraint FK1A5D1721374CDDF5;
alter table RESPOSTA drop constraint FK1A5D1721F603D5DF;
alter table RESPOSTA drop constraint FK1A5D1721E175AEFF;
alter table TURMA drop constraint FK4C79745374CDDF5;
alter table TURMA drop constraint FK4C79745E4E231F3;
drop table ALTERNATIVA cascade;
drop table ALUNO cascade;
drop table ALUNO_QUESTIONARIO cascade;
drop table ALUNO_TURMA cascade;
drop table DISCIPLINA cascade;
drop table PROFESSOR cascade;
drop table QUESTAO cascade;
drop table QUESTAO_ALTERNATIVA cascade;
drop table QUESTIONARIO cascade;
drop table QUESTIONARIO_RESPOSTA cascade;
drop table RESPOSTA cascade;
drop table SEMESTRE_LETIVO cascade;
drop table TURMA cascade;
drop table USUARIO cascade;
drop sequence hibernate_sequence;
create table ALTERNATIVA (id  bigserial not null, descricao varchar(255), primary key (id));
create table ALUNO (matricula varchar(255), id int8 not null, primary key (id));
create table ALUNO_QUESTIONARIO (ALUNO_id int8 not null, questionarios_id int8 not null, unique (questionarios_id));
create table ALUNO_TURMA (ALUNO_id int8 not null, turmas_id int4 not null, primary key (ALUNO_id, turmas_id));
create table DISCIPLINA (codigo varchar(255) not null, nomeDisciplina varchar(255), primary key (codigo));
create table PROFESSOR (matricula varchar(255), id int8 not null, primary key (id));
create table QUESTAO (id  bigserial not null, descricao varchar(255), primary key (id));
create table QUESTAO_ALTERNATIVA (QUESTAO_id int8 not null, alternativas_id int8 not null);
create table QUESTIONARIO (id int8 not null, aluno_id int8, semestreLetivo_id int4, turma_id int4, primary key (id));
create table QUESTIONARIO_RESPOSTA (QUESTIONARIO_id int8 not null, respostas_id int8 not null, unique (respostas_id));
create table RESPOSTA (id  bigserial not null, numero int8 not null, alternativa_id int8, questao_id int8, semestreLetivo_id int4, turma_id int4, primary key (id));
create table SEMESTRE_LETIVO (id  serial not null, ano int4 not null, semestre int4 not null, primary key (id));
create table TURMA (id  serial not null, codigo varchar(255), disciplina_codigo varchar(255), semestreLetivo_id int4, primary key (id));
create table USUARIO (id  bigserial not null, login varchar(255), nome varchar(255), senha varchar(255), primary key (id));
alter table ALUNO add constraint FK3B7CCCBA49A6E6E foreign key (id) references USUARIO;
alter table ALUNO_QUESTIONARIO add constraint FKD7B490F18066DC foreign key (questionarios_id) references QUESTIONARIO;
alter table ALUNO_QUESTIONARIO add constraint FKD7B490F153CA793F foreign key (ALUNO_id) references ALUNO;
alter table ALUNO_TURMA add constraint FK2F23C2D1D07D5016 foreign key (turmas_id) references TURMA;
alter table ALUNO_TURMA add constraint FK2F23C2D153CA793F foreign key (ALUNO_id) references ALUNO;
alter table PROFESSOR add constraint FK69F5E64FA49A6E6E foreign key (id) references USUARIO;
alter table QUESTAO_ALTERNATIVA add constraint FKF6AFF23AF603D5DF foreign key (QUESTAO_id) references QUESTAO;
alter table QUESTAO_ALTERNATIVA add constraint FKF6AFF23A5F49DEDE foreign key (alternativas_id) references ALTERNATIVA;
alter table QUESTIONARIO add constraint FK7FE291FD374CDDF5 foreign key (semestreLetivo_id) references SEMESTRE_LETIVO;
alter table QUESTIONARIO add constraint FK7FE291FD53CA793F foreign key (aluno_id) references ALUNO;
alter table QUESTIONARIO add constraint FK7FE291FDE175AEFF foreign key (turma_id) references TURMA;
alter table QUESTIONARIO_RESPOSTA add constraint FK63C7A3232FB1E4A4 foreign key (respostas_id) references RESPOSTA;
alter table QUESTIONARIO_RESPOSTA add constraint FK63C7A323253A7595 foreign key (QUESTIONARIO_id) references QUESTIONARIO;
alter table RESPOSTA add constraint FK1A5D1721E210B8BF foreign key (alternativa_id) references ALTERNATIVA;
alter table RESPOSTA add constraint FK1A5D1721374CDDF5 foreign key (semestreLetivo_id) references SEMESTRE_LETIVO;
alter table RESPOSTA add constraint FK1A5D1721F603D5DF foreign key (questao_id) references QUESTAO;
alter table RESPOSTA add constraint FK1A5D1721E175AEFF foreign key (turma_id) references TURMA;
alter table TURMA add constraint FK4C79745374CDDF5 foreign key (semestreLetivo_id) references SEMESTRE_LETIVO;
alter table TURMA add constraint FK4C79745E4E231F3 foreign key (disciplina_codigo) references DISCIPLINA;
create sequence hibernate_sequence;
